const list = [ 
{
    id: 1,
    symbol: "images/veg.png",
    name: "Veg Briyani",
    starRate: "images/star.png",
    price: 60,
    image: "images/food.png",
    count: 1,
},
{
    id: 2,
    symbol: "images/veg.png",
    name: "Sweet lime",
    starRate: "images/star.png",
    price: 40,
    image: "images/food.png",
    count: 1,
},
{
    id: 3,
    symbol: "images/veg.png",
    name: "Veg fried Rice",
    starRate: "images/star.png",
    price: 80,
    image: "images/food.png",
    count: 1,
},
{
    id: 4,
    symbol: "images/veg.png",
    name: "Veg Noodles",
    starRate: "images/star.png",
    price: 120,
    image: "images/food.png",
    count: 1,
},
{
    id: 5,
    symbol: "images/veg.png",
    name: "Gobi 65",
    starRate: "images/star.png",
    price: 60,
    image: "images/food.png",
    count: 1,
},
{
    id: 6,
    symbol: "images/veg.png",
    name: "Chilli Parotta",
    starRate: "images/star.png",
    price: 70,
    image: "images/food.png",
    count: 1,
},
{
    id: 7,
    symbol: "images/veg.png",
    name: "Veg kuruma",
    starRate: "images/star.png",
    price: 60,
    image: "images/food.png",
    count: 1,
},
{
    id: 8,
    symbol: "images/veg.png",
    name: "Paneer Fried Rice",
    starRate: "images/star.png",
    price: 120,
    image: "images/food.png",
    count: 1,
},
{
    id: 9,
    symbol: "images/veg.png",
    name: "Paneer Butter Masala",
    starRate: "images/star.png",
    price: 140,
    image: "images/food.png",
    count: 1,
},
{
    id: 10,
    symbol: "images/veg.png",
    name: "Veg fried Rice",
    starRate: "images/star.png",
    price: 80,
    image: "images/food.png",
    count: 1,
},
{
    id: 11,
    symbol: "images/veg.png",
    name: "Veg Noodles",
    starRate: "images/star.png",
    price: 120,
    image: "images/food.png",
    count: 1,
},
{
    id: 12,
    symbol: "images/veg.png",
    name: "Gobi 65",
    starRate: "images/star.png",
    price: 60,
    image: "images/food.png",
    count: 1,
},
{
    id: 13,
    symbol: "images/veg.png",
    name: "Chilli Parotta",
    starRate: "images/star.png",
    price: 70,
    image: "images/food.png",
    count: 1,
},
{
    id: 14,
    symbol: "images/veg.png",
    name: "Veg kuruma",
    starRate: "images/star.png",
    price: 60,
    image: "images/food.png",
    count: 1,
}
]

export default list